# Classes
class TennisPlayer
  attr_accessor name: untyped
  attr_accessor level: untyped
  def initialize: (name: untyped, level: untyped) -> void
  def spin: (direction: untyped) -> untyped
  def slice: (direction: untyped) -> untyped
  def analyze: -> {forehand: Integer, backhand: Integer, serve: Integer, description: String}
end
